changelog:
  categories:
    - title: New Features & Improvements ⭐
      labels:
        - enhancement
    - title: Fixes 🛠️
      labels:
        - bug
    - title: Other Changes 📄
      labels:
        - "*"
