name: "Export Release"

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Which version you want to release?"
        required: true
        default: "v0.0.1"

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: game
  PROJECT_PATH: project

permissions:
  packages: write
  contents: write

  #pull-requests: read
  
jobs:
  export:
    name: ${{ matrix.os }}-Export
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: 🪟 Windows
            platform_name: "Windows Desktop"
            artifact_name: windows
            file_extension: .exe
          - os: 🐧 Linux
            platform_name: "Linux/X11"
            artifact_name: linux
            file_extension: .x86_64
          - os: 🍏 Mac
            platform_name: "macOS"
            artifact_name: mac
            file_extension: .zip

    container:
      image: barichello/godot-ci:4.2.2 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.artifact_name }}
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "${{ matrix.platform_name }}" ../build/${{ matrix.artifact_name }}/$EXPORT_NAME${{ matrix.file_extension }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-${{ github.event.inputs.semver }}-release
          path: build/${{ matrix.artifact_name }}
