name: "🏁 Windows"

on:
  workflow_call:
    inputs:
      export-mode:
        type: string
        required: true

jobs:
  linux-build:
    name: "🏁 Windows"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.3.0-beta.3"
          use-dotnet: false
          include-templates: true
          cache: false

      - name: Build Debug
        run: |
          mkdir -v -p build/windows
          cd project
          godot --headless --verbose --import --export-${{ inputs.export-mode }} "Windows Desktop" ../build/windows/windows-${{ inputs.export-mode }}.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "windows-${{ inputs.export-mode }}"
          path: "build/windows"
